name: Publish NuGet Package

on:
  push:
    tags:
      - 'v*'  # Pubblica solo quando viene creato un tag come v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Extract version from tag
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV     

    - name: Pack
      run: dotnet pack ./LT.HttpClientHelper/LT.HttpClientHelper.csproj --configuration Release /p:PackageVersion=${{ env.PACKAGE_VERSION }} --output ./nupkgs

    - name: Publish to NuGet
      run: dotnet nuget push ./nupkgs/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json